apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: keycloak
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: https
      nodePort: 32222
      port: 443
      protocol: TCP
      targetPort: https
  selector:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: NodePort
