apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-minio-2
spec:
  secretName: tls-minio-2
  dnsNames:
    - minio-dms-1-console
    - minio-dms-1-console.minio-dms.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging