apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress-console
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - minio-console.ncode.local
    secretName: minio-console.ncode.local-tls
  rules:
    - host: minio-console.ncode.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-dms-1-console
                port:
                  number: 9443
