apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  generation: 1
  name: minio-dms-1
  namespace: minio-dms
scheduler:
  name: ""
spec:
  configuration:
    name: minio-dms-1-env-configuration
  credsSecret:
    name: minio-dms-1-secret
  exposeServices:
    console: true
    minio: true
  image: minio/minio:RELEASE.2021-10-13T00-23-17Z
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 5
    db:
      resources: {}
      volumeClaimTemplate:
        metadata:
          name: minio-dms-1-log
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "5368709120"
          storageClassName: local-storage
        status: {}
    resources: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-dms-1
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources:
      limits:
        memory: 32Gi
      requests:
        memory: 2Gi
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1342177280"
        storageClassName: local-storage
      status: {}
    volumesPerServer: 2
  prometheus:
    diskCapacityGB: 5
    resources: {}
    storageClassName: local-storage
  requestAutoCert: true
  users:
  - name: minio-dms-1-user-0