apiVersion: v1
kind: Service
metadata:
  name: minio-port
  namespace: storage
spec:
  ports:
  - nodePort: 31313
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    "v1.min.io/tenant": minio-tenant-1
  type: NodePort
